source 'http://git.houyicloud.com/tangyujie/hyspecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '10.0'

target 'HYCloudChain_Example' do
  pod 'HYCloudChain', :path => '../'

  target 'HYCloudChain_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
